
site_name: Computational Light Laboratory at University College London 
site_description: The computational light laboratory at University College London.
site_author: Kaan Akşit
site_url: 'https://complightlab.com'

repo_name: complight
repo_url: 'https://github.com/complight'

copyright: 'Copyright &copy; 2022'

nav:
  - Home: 'index.md'
  - People:
    - Current members and alumni: 'people/index.md'
  - Timeline: 
    - Recent news: 'timeline/index.md'
  - Publications:
    - List of publications: 'publications/index.md'
    - Realistic Defocus for Multiplane Computer-Generated Holography: 'publications/realistic_defocus_cgh.md'
  - Teaching:
    - Lectures: 'teaching/index.md'
    - SIGGRAPH 2022 Optimizing Vision and Visuals: 'teaching/siggraph2022_optimizing_vision_and_visuals.md'
    - COMP0160 Perception and Interfaces: 'teaching/comp0160_perception_and_interfaces.md'
  - Documentation:
    - List: 'documentation/index.md'
    - Become a doctoral student: 'documentation/become_phd_student.md'
    - Welcome aboard!: 'documentation/getting_started.md'
    - Our laboratory's logo: 'documentation/logo.md'
  - Seminars:
    - Recent seminars: 'seminars/index.md'
  - Research hub: 'research_hub.md'

theme:
    name: material
    custom_dir: overrides
    logo: logo/logo.png
    icon:
      logo: logo
    language: en
    features:
        - content.code.annotate
        - content.tabs.link
       # - header.autohide
       # - navigation.expand
        - navigation.indexes
       # - navigation.instant
        - navigation.sections
        - navigation.tabs
       # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
       # - toc.integrate
        - navigation.instant
        - navigation.indexes
        - navigation.top
        - navigation.expand
    palette:
      - scheme: youtube
        primary: light
        toggle:
          icon: material/eye
          name: Switch to dark mode
      - scheme: youtube
        primary: dark
        toggle:
          icon: material/eye
          name: Switch to light mode
    highlightjs: true
    hljs_languages:
        - python

plugins:
   - search

markdown_extensions:
   - toc:
       permalink: true
   - admonition
   - pymdownx.superfences
   - pymdownx.details
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - 'javascripts/config.js'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/complightlab

extra_css:
  - stylesheets/extra.css
