
site_name: Computational Light Laboratory
site_description: Computational Light Laboratory
site_author: Kaan Akşit
site_url: 'https://complightlab.com'

repo_name: complight
repo_url: 'https://github.com/complight'

copyright: 'Copyright &copy; 2022'

nav:
  - Home: 'index.md'
  - People:
    - Current members and alumni: 'people/index.md'
  - Timeline: 
    - Recent news: 'timeline/index.md'
  - Publications:
    - List of publications: 'publications/index.md'
    - Highlighted works:
      - HoloBeam Paper-Thin Near-Eye Displays: 'publications/holobeam.md'
      - Realistic Defocus for Multiplane Computer-Generated Holography: 'publications/realistic_defocus_cgh.md'
      - Optimizing Vision and Visuals: 'teaching/siggraph2022_optimizing_vision_and_visuals.md'
  - Teaching:
    - Courses: 'teaching/index.md'
    - SIGGRAPH 2022 Optimizing Vision and Visuals (Summer 2022):
      - Description: 'teaching/siggraph2022_optimizing_vision_and_visuals.md'
      - Secret link: 'lectures/index.md'
    - COMP0160 Perception and Interfaces (Spring 2022):
      - Description: 'teaching/comp0160_perception_and_interfaces.md'
      - Coursework 1: 'teaching/comp0160_coursework_1.md'
      - Practical: 'teaching/comp0160_practical.md' 
    - COMP088 Introduction to Machine Learning (Winter 2023):
      - How to setup your virtual environment using Visual Studio: 'https://youtu.be/SHdEqM5xydo'
      - How to implement Gradient Descent solver using Numpy: 'https://youtu.be/-ilAaJlUvYI'
      - How to compile your first Perceptron using Numpy: 'https://youtu.be/ENpJoyDc1rg'
      - How to compile your first model in PyTorch: 'https://youtu.be/PunWQMssqPU'
  - Documentation:
    - List: 'documentation/index.md'
    - For candidates:
      - Become a doctoral student: 'documentation/become_phd_student.md'
    - For newcomers:
      - Welcome aboard!: 'documentation/getting_started.md'
      - Our laboratory's logo: 'documentation/logo.md'
      - Explore our completed projects: 'https://complightlab.com/publications/'
      - Explore our codebase: 'https://github.com/complight'
      - Explore our toolkit: 'https://github.com/kaanaksit/odak'
      - Explore our printable designs: 'https://github.com/complight/optomechanics'
      - Learn more about computer-generated holography: 'https://kaanaksit.github.io/odak/cgh/'
      - Tips and tricks for using our 3D printer: 'documentation/3d_printing.md'
  - Seminars:
    - Description: 'seminars/index.md'
    - Join our mailing List: 'https://www.mailinglists.ucl.ac.uk/mailman/listinfo/high-beams-seminars'
  - Research hub:
    - Description: 'research_hub.md'
    - Join our Slack channels: 'https://join.slack.com/t/rpcdrendering-m4b9370/shared_invite/zt-13b5caruu-o7Ra99nEXkntnJqVYJTVdg'

theme:
    name: material
    custom_dir: overrides
    logo: logo/logo.png
    icon:
      logo: logo
    language: en
    features:
        - content.code.annotate
        - content.tabs.link
       # - header.autohide
       # - navigation.expand
        - navigation.indexes
       # - navigation.instant
        - navigation.sections
        - navigation.tabs
       # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
       # - toc.integrate
        - navigation.instant
        - navigation.indexes
        - navigation.top
        - navigation.expand
    palette:
      - scheme: youtube
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    highlightjs: true
    hljs_languages:
        - python

plugins:
   - search

markdown_extensions:
   - toc:
       permalink: true
   - admonition
   - pymdownx.superfences
   - pymdownx.details
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - 'javascripts/config.js'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/complightlab

extra_css:
  - stylesheets/extra.css
